version: '3.1'
services:
    db:
        image: mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: StreamingSaver
        ports:
            - "3306:3306"
        volumes:
            - streaming-saver:/var/lib/mysql

volumes:
    streaming-saver: